Add path of failing pubspec.yaml on YamlException
dart-lang/bazel pull request #63
Opened 2016-11-01 18:22 UTC by matanlurey

This makes debugging https://github.com/dart-lang/bazel/issues/61 easier.

2016-11-01 19:50 UTC, natebosch commented
Can you give an example of what the error looks like with the latest bazel? I don't think we should see the stack trace anymore - what do we see instead?

2016-11-01 20:06 UTC, natebosch requested changes

2016-11-01 20:06 UTC, natebosch commented on lib/src/bazelify/build.dart
> +      throw new YamlException(
how about handling this in Pubspec.fromPackageDir?

2016-11-02 02:02 UTC, matanlurey commented
@natebosch The error is "nicer" but you still lost context on what path was being traversed.

I'll make the change to move the try/catch into `fromPackageDir`.

2016-11-22 07:02 UTC, matanlurey commented
Closing for now. I'll re-open if this is still an issue.

2016-11-22 07:02 UTC, closed without merging